package simu.model;

import simu.framework.IEventType;

public enum EventType implements IEventType {
    ARR1, SECURITY1, SECURITY2, SECURITY3, SECURITY4, SECURITY5, TICKET_SELL1, TICKET_SELL2, TICKET_SELL3, TICKET_SELL4, CHECK_IN1, CHECK_IN2, CHECK_IN3, CHECK_IN4, CHECK_IN5, CATERING1, CATERING2, CATERING3, CATERING4, CUSTOMER_ARRIVAL, VIP_CUSTOMER_ARRIVAL;
}